### ISSUE TITLE
Providing few-shot examples?

### ISSUE THREAD

**Issue by rmitsch** [Knowledgator/GLiClass#10]
Is there a way to do few-shotting with `gliclass`? I.e. something between zero-shotting and fine-tuning my model.

Thanks for the great work!

**Comment by Ingvarstep** [comment]
@rmitsch , great question, currently `gliclass` doesn't support it, but this is what we are actively working on. However, you can fine-tune the model with a few examples and get good performance right now.

**Comment by rmitsch** [comment]
Gotcha, thanks!
